# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Victor Melnyk
email: victor.melnyk.vm@gmail.com
# this means to ignore newlines until "baseurl:"
description: > Victor Melnyk blog
# the subpath of your site, e.g. /blog
baseurl: "/flit"
# the base hostname & protocol for your site
url: "http://flit.pro"
twitter_username: ""
github_username: victormelnyk

# Build settings
markdown: kramdown
